<a href="https://colab.research.google.com/github/mostafizcse007/Machine-Learning/blob/main/Week%206/xgboost_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import optuna

from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split,KFold, cross_val_score
from sklearn.metrics import r2_score
from xgboost import XGBRegressor,callback
import xgboost

In [77]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')

In [78]:
ids = test['id']

In [79]:
train.drop(columns=['id'],inplace = True)
test.drop(columns=['id'],inplace = True)

In [80]:
train = pd.get_dummies(data=train,columns=['Sex'],drop_first=True,dtype=int)
test = pd.get_dummies(data=test,columns=['Sex'],drop_first=True,dtype=int)

In [81]:
train.head()

,Length,Diameter,Height,Weight,Shucked Weight,Viscera Weight,Shell Weight,Age,Sex_I,Sex_M
0,1.6000,1.2500,0.5750,43.700754,15.025235,10.262519,13.324265,17.0,0,0
1,1.5750,1.1625,0.3750,32.417653,12.927372,6.208540,8.930093,20.0,0,1
2,1.6125,1.2750,0.4375,34.373769,14.784264,9.142714,10.772810,10.0,0,0
3,1.2250,0.9875,0.3250,18.455524,8.037083,3.926406,4.819415,9.0,0,1
4,1.3750,1.0250,0.3875,22.736299,9.879801,5.513978,6.945627,10.0,1,0

In [82]:
X,y = train.drop(columns=['Age']),train['Age']

In [83]:
X_train_full,X_test,y_train_full,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [84]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, test_size=0.25, random_state=42
)

In [85]:
def objective(trial):
  params = {
      "objective":"reg:squarederror",
      "eval_metric":"mae",
      "tree_method":"hist",
      "random_state":42,
      "verbosity":0,
      "max_depth":trial.suggest_int("max_depth",3,15,step=1),
      "n_estimators":trial.suggest_int("n_estimators",100,5000,step=100),
      "learning_rate":trial.suggest_float("learning_rate",1e-3,0.3,log=True),
      "min_child_weight":trial.suggest_int("min_child_weight",1,20),
      "gamma":trial.suggest_float("gamma",1.0,10.0),
      "subsample":trial.suggest_float("subsample",0.5,1.0),
      "colsample_bytree":trial.suggest_float("colsample_bytree",0.5,1.0),
      "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
      "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True)
  }

  es = xgboost.callback.EarlyStopping(
    rounds=50,
    save_best=True
 )
  clf = XGBRegressor(tree_method="hist", device="cuda", callbacks=[es])
  clf.fit(X_train,y_train,eval_set=[(X_valid,y_valid)])
  y_pred = clf.predict(X_valid)
  score = r2_score(y_valid,y_pred)
  return score

In [86]:
study = optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=50)

[I 2026-03-20 15:15:07,890] A new study created in memory with name: no-name-b2f15553-c88f-4561-94e4-ee4ba9d072bb

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:08,167] Trial 0 finished with value: 0.5955685956657008 and parameters: {'max_depth': 11, 'n_estimators': 4700, 'learning_rate': 0.05532932798000539, 'min_child_weight': 15, 'gamma': 1.356098712183698, 'subsample': 0.581094517772616, 'colsample_bytree': 0.7659330310384236, 'reg_alpha': 1.351853793308209, 'reg_lambda': 0.36773855146634393}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:08,441] Trial 1 finished with value: 0.5955685956657008 and parameters: {'max_depth': 14, 'n_estimators': 3800, 'learning_rate': 0.12132613069918431, 'min_child_weight': 15, 'gamma': 8.012522557395837, 'subsample': 0.580493013585357, 'colsample_bytree': 0.5448908179173628, 'reg_alpha': 1.819874390309593e-05, 'reg_lambda': 1.0175412298841808e-07}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:08,689] Trial 2 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 4300, 'learning_rate': 0.01091442739503, 'min_child_weight': 15, 'gamma': 4.526205044082779, 'subsample': 0.7808540769658829, 'colsample_bytree': 0.8698170013378997, 'reg_alpha': 1.2418082799893004e-07, 'reg_lambda': 0.00016505661879127775}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:08,954] Trial 3 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 2400, 'learning_rate': 0.003804274028959977, 'min_child_weight': 7, 'gamma': 9.621020394832243, 'subsample': 0.6729019702326611, 'colsample_bytree': 0.7977001211540635, 'reg_alpha': 0.003685220401808338, 'reg_lambda': 1.6867221361152083}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:09,199] Trial 4 finished with value: 0.5955685956657008 and parameters: {'max_depth': 5, 'n_estimators': 3200, 'learning_rate': 0.15523668168447421, 'min_child_weight': 8, 'gamma': 7.8592230502622575, 'subsample': 0.5006964735883794, 'colsample_bytree': 0.8097299632488384, 'reg_alpha': 6.366640585284634e-07, 'reg_lambda': 0.00021179106205721927}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:09,459] Trial 5 finished with value: 0.5955685956657008 and parameters: {'max_depth': 14, 'n_estimators': 2700, 'learning_rate': 0.10133733057129825, 'min_child_weight': 10, 'gamma': 5.334745206864209, 'subsample': 0.7039786588312401, 'colsample_bytree': 0.9266928357918298, 'reg_alpha': 2.08687750918244e-08, 'reg_lambda': 0.08725503235981209}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:09,704] Trial 6 finished with value: 0.5955685956657008 and parameters: {'max_depth': 5, 'n_estimators': 3900, 'learning_rate': 0.0852319116503163, 'min_child_weight': 11, 'gamma': 4.634130574785528, 'subsample': 0.6356977872907951, 'colsample_bytree': 0.5991637495550448, 'reg_alpha': 2.779670007011811e-08, 'reg_lambda': 1.0502057133455121e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:09,954] Trial 7 finished with value: 0.5955685956657008 and parameters: {'max_depth': 12, 'n_estimators': 300, 'learning_rate': 0.008312857229614922, 'min_child_weight': 5, 'gamma': 8.416325266111869, 'subsample': 0.5015649953640458, 'colsample_bytree': 0.7794607769461079, 'reg_alpha': 0.06067439689778425, 'reg_lambda': 1.693591810892002e-08}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:10,217] Trial 8 finished with value: 0.5955685956657008 and parameters: {'max_depth': 9, 'n_estimators': 3300, 'learning_rate': 0.003403972219924039, 'min_child_weight': 13, 'gamma': 3.434604865598835, 'subsample': 0.8226400522527053, 'colsample_bytree': 0.6187970145614694, 'reg_alpha': 1.266174463003026e-08, 'reg_lambda': 0.4466608585326137}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:10,485] Trial 9 finished with value: 0.5955685956657008 and parameters: {'max_depth': 7, 'n_estimators': 2200, 'learning_rate': 0.01282903901008082, 'min_child_weight': 8, 'gamma': 7.621873964621049, 'subsample': 0.8150399921317886, 'colsample_bytree': 0.6837171264234527, 'reg_alpha': 2.2508622625991924e-07, 'reg_lambda': 6.803078804838391e-06}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:10,775] Trial 10 finished with value: 0.5955685956657008 and parameters: {'max_depth': 11, 'n_estimators': 4800, 'learning_rate': 0.046912228020452244, 'min_child_weight': 19, 'gamma': 1.4774747166120952, 'subsample': 0.9766842636753861, 'colsample_bytree': 0.9987028218157845, 'reg_alpha': 2.4052391349719273, 'reg_lambda': 0.01643797560908666}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:11,048] Trial 11 finished with value: 0.5955685956657008 and parameters: {'max_depth': 15, 'n_estimators': 5000, 'learning_rate': 0.28786590063175066, 'min_child_weight': 17, 'gamma': 1.5602009520113955, 'subsample': 0.5989072814703074, 'colsample_bytree': 0.5363019099673176, 'reg_alpha': 3.806328608215774e-05, 'reg_lambda': 1.1584477070880415e-08}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:11,322] Trial 12 finished with value: 0.5955685956657008 and parameters: {'max_depth': 12, 'n_estimators': 4000, 'learning_rate': 0.0466749004169209, 'min_child_weight': 2, 'gamma': 6.523104314877577, 'subsample': 0.5765397610183907, 'colsample_bytree': 0.7002897660462184, 'reg_alpha': 3.9389161577959364e-05, 'reg_lambda': 9.304214669538581}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:11,599] Trial 13 finished with value: 0.5955685956657008 and parameters: {'max_depth': 13, 'n_estimators': 700, 'learning_rate': 0.032378959576640845, 'min_child_weight': 15, 'gamma': 3.090299761475918, 'subsample': 0.5843135963865873, 'colsample_bytree': 0.537230660207092, 'reg_alpha': 6.971214259592732, 'reg_lambda': 0.006161369109315634}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:11,870] Trial 14 finished with value: 0.5955685956657008 and parameters: {'max_depth': 10, 'n_estimators': 1700, 'learning_rate': 0.2870702071242039, 'min_child_weight': 20, 'gamma': 9.878830221082017, 'subsample': 0.9358283043847077, 'colsample_bytree': 0.7070980135575843, 'reg_alpha': 0.0022704098673795798, 'reg_lambda': 5.387342223449864e-07}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:12,154] Trial 15 finished with value: 0.5955685956657008 and parameters: {'max_depth': 15, 'n_estimators': 3500, 'learning_rate': 0.001283541244114436, 'min_child_weight': 16, 'gamma': 6.4873317677643145, 'subsample': 0.720958549837709, 'colsample_bytree': 0.6204253184581983, 'reg_alpha': 6.289441044279963e-06, 'reg_lambda': 0.001904492395352169}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:12,446] Trial 16 finished with value: 0.5955685956657008 and parameters: {'max_depth': 9, 'n_estimators': 4400, 'learning_rate': 0.025162052612410207, 'min_child_weight': 13, 'gamma': 2.6719425494235196, 'subsample': 0.5454126577618039, 'colsample_bytree': 0.8691141122307722, 'reg_alpha': 0.17409664987527113, 'reg_lambda': 2.534967774962286e-07}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:12,725] Trial 17 finished with value: 0.5955685956657008 and parameters: {'max_depth': 13, 'n_estimators': 4600, 'learning_rate': 0.0895603839743475, 'min_child_weight': 18, 'gamma': 6.749274301716386, 'subsample': 0.674417760361511, 'colsample_bytree': 0.7442217723684192, 'reg_alpha': 0.0009119072564221207, 'reg_lambda': 1.6598636406604894e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:13,006] Trial 18 finished with value: 0.5955685956657008 and parameters: {'max_depth': 8, 'n_estimators': 3800, 'learning_rate': 0.1757538397059479, 'min_child_weight': 13, 'gamma': 8.43556865470703, 'subsample': 0.89039399112881, 'colsample_bytree': 0.6573354221287829, 'reg_alpha': 0.02898766662510513, 'reg_lambda': 0.056300048442854564}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:13,365] Trial 19 finished with value: 0.5955685956657008 and parameters: {'max_depth': 11, 'n_estimators': 2800, 'learning_rate': 0.055811701935369114, 'min_child_weight': 11, 'gamma': 3.996859260224028, 'subsample': 0.6556170973532656, 'colsample_bytree': 0.5002032906789944, 'reg_alpha': 0.00010260932624646373, 'reg_lambda': 3.56078038445921e-07}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:13,731] Trial 20 finished with value: 0.5955685956657008 and parameters: {'max_depth': 14, 'n_estimators': 1600, 'learning_rate': 0.025755300874189473, 'min_child_weight': 17, 'gamma': 5.566932705331322, 'subsample': 0.6275786740110566, 'colsample_bytree': 0.7448310253316809, 'reg_alpha': 2.648846416359682e-06, 'reg_lambda': 0.0011279765766226395}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:14,134] Trial 21 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 4400, 'learning_rate': 0.01168511780317756, 'min_child_weight': 15, 'gamma': 2.272419749853724, 'subsample': 0.7704182888203154, 'colsample_bytree': 0.8774718755394912, 'reg_alpha': 2.5011922977359607e-07, 'reg_lambda': 0.00012732391647739534}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:14,492] Trial 22 finished with value: 0.5955685956657008 and parameters: {'max_depth': 6, 'n_estimators': 4200, 'learning_rate': 0.00542014321839688, 'min_child_weight': 14, 'gamma': 4.428415530318541, 'subsample': 0.7702591776496878, 'colsample_bytree': 0.853220477962804, 'reg_alpha': 6.002004982377148e-06, 'reg_lambda': 4.257013059423808e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:14,900] Trial 23 finished with value: 0.5955685956657008 and parameters: {'max_depth': 10, 'n_estimators': 5000, 'learning_rate': 0.019515989768890542, 'min_child_weight': 18, 'gamma': 1.1145759938773279, 'subsample': 0.8394646926515682, 'colsample_bytree': 0.9202568041291174, 'reg_alpha': 0.013130322486644039, 'reg_lambda': 2.9315922165532105e-06}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:15,300] Trial 24 finished with value: 0.5955685956657008 and parameters: {'max_depth': 7, 'n_estimators': 3700, 'learning_rate': 0.13635714749170688, 'min_child_weight': 15, 'gamma': 5.416997868968682, 'subsample': 0.7451732165516326, 'colsample_bytree': 0.9886595947801204, 'reg_alpha': 0.00031635913092545353, 'reg_lambda': 0.0007180730220175015}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:15,662] Trial 25 finished with value: 0.5955685956657008 and parameters: {'max_depth': 12, 'n_estimators': 3100, 'learning_rate': 0.06904438719969071, 'min_child_weight': 12, 'gamma': 2.2023273373196823, 'subsample': 0.5528534621847428, 'colsample_bytree': 0.8177881497352621, 'reg_alpha': 0.5704068297698791, 'reg_lambda': 5.415812012286029e-08}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:16,023] Trial 26 finished with value: 0.5955685956657008 and parameters: {'max_depth': 10, 'n_estimators': 4200, 'learning_rate': 0.001530744399638329, 'min_child_weight': 16, 'gamma': 9.287324876579593, 'subsample': 0.8880005483733738, 'colsample_bytree': 0.9142257310372566, 'reg_alpha': 8.741765246940878e-07, 'reg_lambda': 1.6679598107725778e-06}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:16,439] Trial 27 finished with value: 0.5955685956657008 and parameters: {'max_depth': 4, 'n_estimators': 4600, 'learning_rate': 0.03618099248062481, 'min_child_weight': 20, 'gamma': 3.65477582438162, 'subsample': 0.5376125052251387, 'colsample_bytree': 0.7697946084990058, 'reg_alpha': 1.1061341446730859e-07, 'reg_lambda': 0.6849954959700373}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:17,112] Trial 28 finished with value: 0.5955685956657008 and parameters: {'max_depth': 14, 'n_estimators': 3700, 'learning_rate': 0.007916325025328061, 'min_child_weight': 9, 'gamma': 7.071222424052767, 'subsample': 0.6181104631217579, 'colsample_bytree': 0.8298641544304605, 'reg_alpha': 9.925837024569914e-06, 'reg_lambda': 5.564781628299381e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:18,342] Trial 29 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 2100, 'learning_rate': 0.002541627516530954, 'min_child_weight': 6, 'gamma': 5.997971398234321, 'subsample': 0.6790200107523973, 'colsample_bytree': 0.9518585167527797, 'reg_alpha': 0.0072824662635120165, 'reg_lambda': 0.0055828569657152575}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:19,064] Trial 30 finished with value: 0.5955685956657008 and parameters: {'max_depth': 8, 'n_estimators': 4200, 'learning_rate': 0.01781250250272938, 'min_child_weight': 14, 'gamma': 9.194536506612291, 'subsample': 0.7967192921381182, 'colsample_bytree': 0.7260547538115282, 'reg_alpha': 0.0003806163562908149, 'reg_lambda': 3.1072286967042384}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:19,743] Trial 31 finished with value: 0.5955685956657008 and parameters: {'max_depth': 4, 'n_estimators': 3100, 'learning_rate': 0.0040826654078890265, 'min_child_weight': 6, 'gamma': 7.976472138853884, 'subsample': 0.5013235680991525, 'colsample_bytree': 0.7942470239227789, 'reg_alpha': 0.5984757306435252, 'reg_lambda': 0.6155661359433638}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:20,523] Trial 32 finished with value: 0.5955685956657008 and parameters: {'max_depth': 5, 'n_estimators': 2400, 'learning_rate': 0.17794411360149695, 'min_child_weight': 3, 'gamma': 9.59994445154246, 'subsample': 0.7107458893757621, 'colsample_bytree': 0.8239370478310702, 'reg_alpha': 0.002061063679208929, 'reg_lambda': 0.07635541045132836}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:20,959] Trial 33 finished with value: 0.5955685956657008 and parameters: {'max_depth': 4, 'n_estimators': 1300, 'learning_rate': 0.006627809062074167, 'min_child_weight': 8, 'gamma': 4.834244975620723, 'subsample': 0.6498295180907513, 'colsample_bytree': 0.8901674998659611, 'reg_alpha': 1.3510354656581716e-06, 'reg_lambda': 2.37440909045644}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:21,543] Trial 34 finished with value: 0.5955685956657008 and parameters: {'max_depth': 6, 'n_estimators': 2800, 'learning_rate': 0.012531356151506813, 'min_child_weight': 9, 'gamma': 8.589510163396355, 'subsample': 0.6812851395425418, 'colsample_bytree': 0.8446964461584259, 'reg_alpha': 8.85601794732871e-08, 'reg_lambda': 0.13892680219920422}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:22,023] Trial 35 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 3500, 'learning_rate': 0.001953696211844307, 'min_child_weight': 10, 'gamma': 7.508044796246704, 'subsample': 0.6105539085890226, 'colsample_bytree': 0.7789752902774463, 'reg_alpha': 0.06101051854733919, 'reg_lambda': 0.0236008245063863}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:22,335] Trial 36 finished with value: 0.5955685956657008 and parameters: {'max_depth': 5, 'n_estimators': 2500, 'learning_rate': 0.003929654912387318, 'min_child_weight': 4, 'gamma': 8.834465260918227, 'subsample': 0.7382183793744254, 'colsample_bytree': 0.6732717711172675, 'reg_alpha': 7.880857240802023e-05, 'reg_lambda': 0.00027825245403024243}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:22,686] Trial 37 finished with value: 0.5955685956657008 and parameters: {'max_depth': 13, 'n_estimators': 4700, 'learning_rate': 0.12756480833877332, 'min_child_weight': 12, 'gamma': 7.80778172874138, 'subsample': 0.5664442935074381, 'colsample_bytree': 0.79779235128891, 'reg_alpha': 5.6641565003667456e-08, 'reg_lambda': 0.25491107502686683}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:23,053] Trial 38 finished with value: 0.5955685956657008 and parameters: {'max_depth': 11, 'n_estimators': 3400, 'learning_rate': 0.002850719156962949, 'min_child_weight': 7, 'gamma': 6.049060153780831, 'subsample': 0.529806476925187, 'colsample_bytree': 0.5804158810922454, 'reg_alpha': 1.0011916807993684e-08, 'reg_lambda': 1.3036340878305182}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:23,391] Trial 39 finished with value: 0.5955685956657008 and parameters: {'max_depth': 6, 'n_estimators': 2000, 'learning_rate': 0.010277176187828845, 'min_child_weight': 12, 'gamma': 4.978082688005179, 'subsample': 0.5954765180392979, 'colsample_bytree': 0.6449290543915781, 'reg_alpha': 1.7000009455543163e-05, 'reg_lambda': 9.256807612404737}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:23,695] Trial 40 finished with value: 0.5955685956657008 and parameters: {'max_depth': 15, 'n_estimators': 4000, 'learning_rate': 0.07150622027717526, 'min_child_weight': 1, 'gamma': 9.953958692002928, 'subsample': 0.6390632931162323, 'colsample_bytree': 0.7599275744664485, 'reg_alpha': 9.996361342895206, 'reg_lambda': 7.837412268074933e-08}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:24,022] Trial 41 finished with value: 0.5955685956657008 and parameters: {'max_depth': 4, 'n_estimators': 3000, 'learning_rate': 0.20124201411774234, 'min_child_weight': 10, 'gamma': 7.21300625096084, 'subsample': 0.5258543785136918, 'colsample_bytree': 0.7996219219233479, 'reg_alpha': 4.311592872034457e-07, 'reg_lambda': 0.00029724395175115823}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:24,370] Trial 42 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 3300, 'learning_rate': 0.11616047482631545, 'min_child_weight': 5, 'gamma': 7.950171864839884, 'subsample': 0.5130495720233531, 'colsample_bytree': 0.7201950115111341, 'reg_alpha': 2.9210765046799686e-08, 'reg_lambda': 0.0040225069279142735}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:24,677] Trial 43 finished with value: 0.5955685956657008 and parameters: {'max_depth': 5, 'n_estimators': 4400, 'learning_rate': 0.22961699947061054, 'min_child_weight': 8, 'gamma': 8.239975939547838, 'subsample': 0.5736237583093089, 'colsample_bytree': 0.8882059501262332, 'reg_alpha': 1.3492785893204943e-06, 'reg_lambda': 2.2758436137115018e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:24,996] Trial 44 finished with value: 0.5955685956657008 and parameters: {'max_depth': 8, 'n_estimators': 5000, 'learning_rate': 0.0976539552862304, 'min_child_weight': 16, 'gamma': 9.26783678906327, 'subsample': 0.6966469503027826, 'colsample_bytree': 0.8513656016103737, 'reg_alpha': 2.494605705880197, 'reg_lambda': 3.565500886325849e-06}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:25,331] Trial 45 finished with value: 0.5955685956657008 and parameters: {'max_depth': 4, 'n_estimators': 3900, 'learning_rate': 0.04213557093371298, 'min_child_weight': 14, 'gamma': 3.216039384120969, 'subsample': 0.5576456355974277, 'colsample_bytree': 0.9542835598842503, 'reg_alpha': 3.721328004026055e-07, 'reg_lambda': 0.027254981579655602}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:25,681] Trial 46 finished with value: 0.5955685956657008 and parameters: {'max_depth': 12, 'n_estimators': 2600, 'learning_rate': 0.06330043697038854, 'min_child_weight': 18, 'gamma': 8.757097415368964, 'subsample': 0.8408560689493941, 'colsample_bytree': 0.8142628280217105, 'reg_alpha': 2.914821371159685e-05, 'reg_lambda': 7.339961866763263e-05}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:26,074] Trial 47 finished with value: 0.5955685956657008 and parameters: {'max_depth': 3, 'n_estimators': 4800, 'learning_rate': 0.15417865724647117, 'min_child_weight': 7, 'gamma': 4.098249866902703, 'subsample': 0.5931437133093839, 'colsample_bytree': 0.7600677013309237, 'reg_alpha': 0.00011975149157375, 'reg_lambda': 0.010718823137163852}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:26,390] Trial 48 finished with value: 0.5955685956657008 and parameters: {'max_depth': 14, 'n_estimators': 3600, 'learning_rate': 0.2461366285399894, 'min_child_weight': 11, 'gamma': 5.9042365086262825, 'subsample': 0.6600283272660039, 'colsample_bytree': 0.6954726420543413, 'reg_alpha': 0.30731779827359323, 'reg_lambda': 0.0018665064198204317}. Best is trial 0 with value: 0.5955685956657008.

[0]	validation_0-rmse:2.60587
[1]	validation_0-rmse:2.31108
[2]	validation_0-rmse:2.15219
[3]	validation_0-rmse:2.07163
[4]	validation_0-rmse:2.02273
[5]	validation_0-rmse:1.99900
[6]	validation_0-rmse:1.99001
[7]	validation_0-rmse:1.98057
[8]	validation_0-rmse:1.98459
[9]	validation_0-rmse:1.98631
[10]	validation_0-rmse:1.98279
[11]	validation_0-rmse:1.98039
[12]	validation_0-rmse:1.98315
[13]	validation_0-rmse:1.98357
[14]	validation_0-rmse:1.98491
[15]	validation_0-rmse:1.98553
[16]	validation_0-rmse:1.98514
[17]	validation_0-rmse:1.98524
[18]	validation_0-rmse:1.98522
[19]	validation_0-rmse:1.98488
[20]	validation_0-rmse:1.98572
[21]	validation_0-rmse:1.98186
[22]	validation_0-rmse:1.98311
[23]	validation_0-rmse:1.98358
[24]	validation_0-rmse:1.98593
[25]	validation_0-rmse:1.98598
[26]	validation_0-rmse:1.98688
[27]	validation_0-rmse:1.98729
[28]	validation_0-rmse:1.98636
[29]	validation_0-rmse:1.98904
[30]	validation_0-rmse:1.99021
[31]	validation_0-rmse:1.99089
[32]	validation_0-rmse:1.99106
[33]	validation_0-rmse:1.99224
[34]	validation_0-rmse:1.99535
[35]	validation_0-rmse:1.99625
[36]	validation_0-rmse:1.99677
[37]	validation_0-rmse:1.99997
[38]	validation_0-rmse:2.00104
[39]	validation_0-rmse:2.00181
[40]	validation_0-rmse:2.00106
[41]	validation_0-rmse:2.00340
[42]	validation_0-rmse:2.00307
[43]	validation_0-rmse:2.00228
[44]	validation_0-rmse:2.00118
[45]	validation_0-rmse:2.00026
[46]	validation_0-rmse:2.00181
[47]	validation_0-rmse:2.00518
[48]	validation_0-rmse:2.00556
[49]	validation_0-rmse:2.00557
[50]	validation_0-rmse:2.00578
[51]	validation_0-rmse:2.00662
[52]	validation_0-rmse:2.00706
[53]	validation_0-rmse:2.00792
[54]	validation_0-rmse:2.01239
[55]	validation_0-rmse:2.01498
[56]	validation_0-rmse:2.01613
[57]	validation_0-rmse:2.01916
[58]	validation_0-rmse:2.02052
[59]	validation_0-rmse:2.02388
[60]	validation_0-rmse:2.02498

[I 2026-03-20 15:15:26,733] Trial 49 finished with value: 0.5955685956657008 and parameters: {'max_depth': 7, 'n_estimators': 4000, 'learning_rate': 0.02445287083469634, 'min_child_weight': 17, 'gamma': 6.65424773326998, 'subsample': 0.8059469778440577, 'colsample_bytree': 0.7372237633294454, 'reg_alpha': 2.726266229822573e-06, 'reg_lambda': 0.2473048568404234}. Best is trial 0 with value: 0.5955685956657008.

In [95]:
study.best_params

{'max_depth': 11,
 'n_estimators': 4700,
 'learning_rate': 0.05532932798000539,
 'min_child_weight': 15,
 'gamma': 1.356098712183698,
 'subsample': 0.581094517772616,
 'colsample_bytree': 0.7659330310384236,
 'reg_alpha': 1.351853793308209,
 'reg_lambda': 0.36773855146634393}

In [96]:
study.best_value

0.5955685956657008

In [97]:
best_params = study.best_params

final_model = XGBRegressor(
    **best_params,
    objective="reg:squarederror",
    eval_metric="mae",
    tree_method="hist",
    verbosity=0,
    random_state=42
)

# train on FULL training data (train + valid)
final_model.fit(X, y)

# evaluate on untouched test set
from sklearn.metrics import r2_score

y_pred = final_model.predict(X_test)
print("Final Test R2:", r2_score(y_test, y_pred))

Final Test R2: 0.93601641852318

In [98]:
values = final_model.predict(test)

In [99]:
df = pd.DataFrame({
    'id':ids,
    'Age':values
})

In [100]:
df.head()

      id        Age
0  15000  14.295913
1  15001  13.036388
2  15002  10.097084
3  15003  10.623096
4  15004   8.399055

In [101]:
df.to_csv('sub_1.csv',index=False)

In [94]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive